### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by RHelmuth** [rmlockwood/FLExTrans#1]
Using the Linux in a subsystem method, I "successfully" got things set up, but when I open FlexTrans I get an import error message. 
![image](https://user-images.githubusercontent.com/32963005/51488834-ee38fe80-1da6-11e9-84be-3ec5da313e03.png)
Any thoughts?
It might be worth mentioning that I'm running Windows in VM on macOS.

Edit: I get the same error every time I "Run All"

**Comment by RHelmuth** [comment]
When I run all I get 2 errors.
![image](https://user-images.githubusercontent.com/32963005/51517533-532e3c00-1e1b-11e9-98cc-f3a54d780bed.png)

**Comment by rmlockwood** [comment]
Try selecting the German Sample project as your database. German is the source project. For some reason you have Swedish selected.

 

FLExTools > Choose Database > German-FLExTrans-Sample

 

Re-run it by clicking the Run All (Modify) button
