### ISSUE TITLE
[Live Rule Tester] First click on window focus switches back to FlexTools

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#105]
This happens for other windows launched from FlexTools. It's annoying as the user has to click again on the tester window.

**Comment by bbryson** [comment]
The FlexTools window also seems to shrink in size when this happens.

My impression is that if I click in the Live Rule Tester at a place where it is not covering the FlexTools window, then the focus doesn't shift, but the size of FlexTools does change.  But I may have imagined that.

**Comment by rmlockwood** [comment]
This happens for all windows that get launched from FLExTools. Settings, Linker Tool, etc.
