### ISSUE TITLE
[Install] Change "Extract Target Lexicon" to "Synthesize Text"

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#163]
When someone is doing transfer, they expect the final stage to be "synthesize the text".  It just happens that "creating the lexicons" is done as part of the same module.   To be more clear to users, maybe the name of the module could be changed.  (But does that create a "migration issue" for existing users, as with #88?  Is there a strategy for that?)

Also suggest removing "a" from "will create a three target language lexicons".

**Comment by rmlockwood** [comment]
fixed in Pull Request #253
