### ISSUE TITLE
Inflection Classes don't appear in STAMP dictionary files

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#164]
Among the ways that synthesis in STAMP determines which allomorph to choose when generating a word, some of the criteria include "allomorph properties" and "morpheme properties" (p. 58 of STAMP manual).  When FLEx is running the AMPLE parser, these are how it implements the "Stem Name" and "Inflection Class" functionalities in the dictionaries used for that process.

Using a FLEx project that has used these mechanisms, the resulting rt and sf dictionaries created by FLExTrans don't include any information about these properties.  This means that STAMP won't be able to generate the correct surface form.

Attaching a sample FLEx project that uses these, along with the rt and sf dictionaries produced by FLExTrans.  Also attaching the *lex.txt file produced by FLEx that serves as the (unified) dictionary for the AMPLE parser in FLEx, to show what these properties look like in that file.  (They are based on the hvo so that's not terribly illuminating to someone trying to read the file.)

Some words to test include:  juego   juegas  in the text   Verbs: Stem-changing

**Comment by bbryson** [comment]
[Spanish-GenerateWords-Experimentlex.txt](https://github.com/rmlockwood/FLExTrans/files/9007126/Spanish-GenerateWords-Experimentlex.txt)
[Spanish-GenerateWords-Experiment_rt.dic.txt](https://github.com/rmlockwood/FLExTrans/files/9007129/Spanish-GenerateWords-Experiment_rt.dic.txt)
[Spanish-GenerateWords-Experiment_sf.dic.txt](https://github.com/rmlockwood/FLExTrans/files/9007130/Spanish-GenerateWords-Experiment_sf.dic.txt)

**Comment by rmlockwood** [comment]
I didn't see a FLEx project attached. It would be helpful.
