### ISSUE TITLE
[Install] Don't call a module FLExTrans.XYZ, just call it XYZ

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#209]
It's confusing to some users to see FLExTrans. in front of each module name. It would be easier to spot modules if they didn't have this prefix.
This would mean installing the modules for FLExTrans directly under FlexTools\Modules. That should work. One issue, though, is where to put the Lib folder. Maybe it could still be in Modules\FLExTrans, but there would be no modules there.

**Comment by bbryson** [comment]
A lot depends on whether the user is already using FLExTools for other things.  If they are, they may have other sets of modules that they want to keep together.  In that case, it's really helpful to have all the FLExTrans modules separate from any other FlexTools modules they may be working on.

**Comment by rmlockwood** [comment]
Any other modules can be under a folder and will get marked with the folder prefix. I’m thinking most people won’t have other FlexTools modules. If they need them, most people will ask folks like us to create one for them.

**Comment by bbryson** [comment]
I just created this issue:

https://github.com/cdfarrow/flextools/issues/20

to request a change in FlexTools.  I think that is a better place to address it.
