### ISSUE TITLE
Shrinking windows when a new window gets displayed

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#211]
There's some kind of issue with scaling either with FLExTools or our modules. When a new window gets launched, like the Live Rule Tester and a person's computer is not set to 100% scaling for their display, the FLExTools window shrinks and the new window gets squished in all of its controls.

**Comment by bbryson** [comment]
I can't realistically set my display to 100%--that makes it too small to read.  I am usually on 150%.

**Comment by bbryson** [comment]
Is this related to the change-of-focus issue, or is that separate?

When I click on the Live Rule Tester or Sense Linker, the FLExTools window comes to the top.  I have to click again to do what I wanted to do in the module.

**Comment by rmlockwood** [comment]
> I can't realistically set my display to 100%--that makes it too small to read. I am usually on 150%.
I just tell people to reduce their resolution.



> Is this related to the change-of-focus issue, or is that separate?
> 
> When I click on the Live Rule Tester or Sense Linker, the FLExTools window comes to the top. I have to click again to do what I wanted to do in the module.

unrelated, see #105

**Comment by rmlockwood** [comment]
Is the normal FlexTools window shrinking? For example if you move it between monitors that have different screen resolutions, does it change it? Is this only a problem with the pyQt windows that we launch?

**Comment by bbryson** [comment]
I'll have to test.

1. When I open a tool, the tool looks fine, but the FLExTools window shrinks.  Do you want a video of it happening?
2. I have not tried moving it from one monitor to another yet.
3.

**Comment by rmlockwood** [comment]
fixed in PR #438
