### ISSUE TITLE
[Sense Linker] Show the text name somewhere at the top

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#213]
Sometimes you are unsure what the name of the text is that your are processing. This would help a lot.

**Comment by bbryson** [comment]
And it would be even better if we could choose the text from here.  In the Sense Linker there is a Choose button that is not active yet.  Something similar could be here.  It would be nice not to have to go over to Settings to choose the text.

**Comment by rmlockwood** [comment]
Please create a separate issue for this. And I think you mean the Live Rule Tester that already has a Choose button.
