### ISSUE TITLE
[Sense Linker] It runs but said it had processed 0 senses

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#233]
There should be more information given as to why 0 senses were processed. This came up in the workshop where it seemed to be that the problem was no morphnames were set (because of a non-English analysis language) in the config. settings.
Something like, 'no morphnames selected as roots, no roots to process. Select the morphnames that count as roots in the Settings tool.'

**Comment by bbryson** [comment]
And ideally it wouldn't just "not open".  It feels like it should still open up, even if it didn't find anything to link.  Let the user see what is coming up, and close it themselves.
