### ISSUE TITLE
[Clean Files] not cleaning correct files

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#235]
I'm using FLExTrans 3.5.5.

I copied the German-Swedish folder (where I had done the test to make sure my install was working).  I renamed it for my languages.  I ran the module Clean Files (version 3.5).  When I look in Build, there are 10 Swedish STAMP files, as well as target_affix_glosses.txt and myText.ana.  Shouldn't all of those be deleted by this module?

**Comment by rmlockwood** [comment]
The module doesn't clear out everything, only select things so that something valuable to the user that might be in the folder isn't touched. We could look for STAMP files, though and delete them regardless of project name.
