### ISSUE TITLE
[Live Rule Tester] The tool doesn't open if the bilingual.dix is missing

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#237]
If the bilingual.dix somehow got deleted, then the Live Rule Tester says it can't open.  The remedy is to run "Extract Bilingual Lexicon" again, but the easiest way to do that is from inside the Live Rule Tester....  It is a hassle to have to run a different module.

Can the Live Rule Tester open anyway, maybe with a message telling the user to click the button to rebuild the lexicon?  Or maybe it should automatically run that module, if it finds that the file is missing.  (Maybe it needs to give a message though, in case there is some problem resulting in it being deleted.  Something like, "Regenerating Bilingual Lexicon".)

**Comment by rmlockwood** [comment]
Pretty sure you mean the Live Rule Tester.
