### ISSUE TITLE
[Run Apertium] Check for attribute values that clash with grammatical categories

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#244]
It's quite easy have an attribute value that is identical to a grammatical category abbreviation (which you have in a_gram_cat). This can cause your rule to not do what you are expecting to do. For example if you have 'n' as a value for gender and 'n' also is for noun, when you try to clip gender for a noun, you will always get 'n' the clip will never see beyond it and get to 'f', 'm' or a 2nd 'n'.

It would be good if the Run Apertium module could give an error when there is an attribute value that clashes with a category abbrev.

**Comment by bbryson** [comment]
Would it also verify that all attribute values are unique, across all attributes?  Or does it already check that?

**Comment by rmlockwood** [comment]
There might be overlap between attribute values, so I don't think we warn about uniqueness here. In the extract bil. lex. module we could do that if we aren't already.
