### ISSUE TITLE
[Live Rule Tester] Allow the transfer to run even with all rules unchecked

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#246]
It's a pain to uncheck all the rules and then to have to check one rule if you just want to see what happens when no rules are processed. Allow the transfer to run without any rules checked. This probably means inserting a dummy rule somehow.

**Comment by bbryson** [comment]
I actually think it would be really useful to have some window where we always show "what this would look like with no rules run".  Right now you have a window just below the source words to show what the "source string" looks like.  Could we do something similar for "target string, with no rules"?
