### ISSUE TITLE
If one module fails, don't continue with remaining modules

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#271]
[Is this a FlexTools issue, not FLExTrans?]

When a user clicks "Run All", if one module fails with an error, the remaining modules still get run.  Because of all the stuff scrolling by in the message window, it is easy to miss the Error messages, or the message that something failed.  It can be hard to figure out what went wrong and where.

It would be better to stop everything if one module fails with a fatal error.

**Comment by bbryson** [comment]
But "skipping sense" shouldn't be considered a fatal error.

**Comment by rmlockwood** [comment]
I think we need this change to be made in FlexTools. I agree with this.

**Comment by bbryson** [comment]
Reported in FlexTools bug tracker.
