### ISSUE TITLE
[install] FlexTools.bat doesn't work well from Config directory

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#272]
Now that the FlexTools.bat file is located in the Config directory, it doesn't need "cd Config" as its first line.

**Comment by rmlockwood** [comment]
Did it not work for you? I think it still needs it because it is being called from the project folder. Of course if you want to troubleshoot, it's more of a pain. You need to be in the project folder and execute: 'Config\FlexTools.bat'

**Comment by bbryson** [comment]
Can we just move it back up to where it was?  I always run it from the DOS box anyway.  It is confusing to have to (a) remember where it is, (b) be in a different directory than it is in, and (c) remember to include Config/   when I call it.  It is really needed, especially when first installing FLExTrans.
