### ISSUE TITLE
stem names might only apply to inflectional affixes

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#281]
I got another error in DoStampSynthesis.py at this line:

            for stemName in stemNameList:
                
                if msa.PartOfSpeechRA == stemName[CATEGORY_STR]:
  
The error message is:
AttributeError: 'MoDerivAffMsa' object has no attribute 'PartOfSpeechRA'

I'm not sure what all the different types of msa are, but in my own version I tried using this at line 271:

    if sense is not None and sense.MorphoSyntaxAnalysisRA.ClassName == 'MoInflAffMsa':

but that may be overly restrictive.

**Comment by bbryson** [comment]
I think this has been fixed.

**Comment by rmlockwood** [comment]
I think this was fixed in 3.6.1
