### ISSUE TITLE
[XXE] Warning msg mentions "pos" instead of "item"

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#313]
In the Transfer Rules file, I wrote a rule that had only one item in the pattern part, but two in the output.  In the output I referred to "item 2".  On validation, there is a warning message that says:

"Warning: the pos attribute refers to a non-existent pattern-item in this rule."

It should say "item" instead of "pos".

**Comment by rmlockwood** [comment]
The attribute really is called pos - short for position. The Apertium dtd defines this and it shouldn't be changed. The css for XXE calls it 'item' for clarity, but the error is still going to refer to the actual attribute.
