### ISSUE TITLE
[install] Provide a way to know what version of FLExTrans I'm running

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#314]
When I install FLExTrans, by default it goes into a folder called "FLExTrans", and when I run it, the title of the window is "FLExTools 2.1.2".  The modules have version numbers on them, but they don't necessarily correlate with the version of FLExTrans.

How can I know what version of FLExTrans I am running?

**Comment by rmlockwood** [comment]
It looks like I could add the FLExTrans version # to version.py, In addition I could put some stuff in the About box about FLExtrans. (Help.py) This stuff would have to get updated each time we do a new release.
