### ISSUE TITLE
[Install] Show the project folder on the status bar

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#334]
It would be nice to somewhere indicate the folder FLExTools was launched from. The FTPaths.CONFIG_PATH has this information in it already. The FLExTools.__UpdateStatusBar() just needs to be updated to show it. 
The install needs to have this code change.
We probably could remove 'Project: xyz' from the status bar, that's redundant since we see it on the DB toolbar button.

**Comment by bbryson** [comment]
Yes, this is helpful!

It might be good if this said "Project folder: "   When I saw it the first time, I thought it was telling me about a FLEx project, and I was wondering, "Is that the source project or the target project?"
