### ISSUE TITLE
Set up attributes for Template Slots

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#339]
Create a module to allow the user to automatically generate one attribute for each slot in a template in the FLEx project, and populate that attribute with the glosses of all the affixes in that slot.

Several caveats:
 - Many users will have templates that are not cleaned up enough for this to work well.  Do we provide certain criteria for deciding when they are ready to run this?
 - If they run it once, and then they improve the templates in FLEx, what happens if they run it again?  Is there a facility for cleaning up what was there?  (delete existing slot attributes and regenerate them?)
 - Do we need a "namespace test", to ensure that no two affixes have the same gloss?  Would this test be run on the values (using info from the LCM) before generating the attributes, so that GUIDs could be used to determine "is this the same affix in more than one slot, or a different affix?"

Issue #229 is similar, but is about Inflection Features and Inflection Classes.  It makes sense to make them separate modules.  It is more likely (early on) that users would need "all the Inflection Features and Classes", regardless of their state of completeness, than that they would need "all template slots and their affixes".

**Comment by rmlockwood** [comment]
Fixed in pull request #376.
