### ISSUE TITLE
Affixes need to allow multiple Stem Names

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#360]
There may be more than one Stem Name that applies to the same affix.  When this is true, there need to be multiple \mp fields added to that affix.  Currently only the last one is getting added.

The attached project includes Stem Names UEirregAR and IEirregIR that both apply to PRS.3SG (for example--there are a lot more as well).  (Delete the .zip from the filename and you will have a valid .fwbackup file.)

Attached is the suffix dictionary that FLExTrans produced, along with the one that I hand edited so it would work, and the identity_rules.t1x file.  (Remove the file extension .txt.)

Also attaching a copy of the project after running FLExTrans with the corrected suffix dictionary. (Delete the .zip from the filename.)

[Spanish-GenerateWords-Experiment_sf.dic-FromFT.txt](https://github.com/rmlockwood/FLExTrans/files/10214025/Spanish-GenerateWords-Experiment_sf.dic-FromFT.txt)

[Spanish-GenerateWords-Experiment_sf.dic-Corrected.txt](https://github.com/rmlockwood/FLExTrans/files/10214026/Spanish-GenerateWords-Experiment_sf.dic-Corrected.txt)

[identity_rules.t1x.txt](https://github.com/rmlockwood/FLExTrans/files/10214057/identity_rules.t1x.txt)

[Spanish-GenerateWords-Experiment 2022-12-12 2127 Ready for test.fwbackup.zip](https://github.com/rmlockwood/FLExTrans/files/10214034/Spanish-GenerateWords-Experiment.2022-12-12.2127.Ready.for.test.fwbackup.zip)

[Spanish-GenerateWords-Experiment 2022-12-12 2126 after test.fwbackup.zip](https://github.com/rmlockwood/FLExTrans/files/10214037/Spanish-GenerateWords-Experiment.2022-12-12.2126.after.test.fwbackup.zip)

**Comment by rmlockwood** [comment]
Good catch!

**Comment by bbryson** [comment]
The new version works!
