### ISSUE TITLE
[Settings] If choose no POS for Synthesis Test, blank line gets written to settings file

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#465]
If I unselect all POS in the "Limit POS" setting for the Synthesis Test, then a blank link gets written to the Config file, and then I can't access the Settings dialog anymore, because "blank lines aren't allowed in the config file".

The same happens if I leave "Max Stems" blank.

Hmm, when I'm setting the LimitLexeme item, if I copy from FLEx, I'm getting a newline at the end of what I'm copy/pasting.  So that is one thing that is putting an extra blank line there.

**Comment by rmlockwood** [comment]
incorporated in PR #475.
I didn't see an issues with the POS list. I think the real issue was the blank line that got created.
FLExTrans will now ignore blank lines and the settings tool will remove whitespace (including newlines) from text, file or folder boxes.
