### ISSUE TITLE
[Transfer Rules] Make "source" and "target" different colors in the clip rules

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#504]
When looking at a rule that has a clip, it's really easy to gloss over the source/target boxes.  If the two values were different colors, it would make it easier to see right away which one is being used.

**Comment by rmlockwood** [comment]
Not possible from what I can tell.

**Comment by rmlockwood** [comment]
AB has a possible solution.

**Comment by rmlockwood** [comment]
Fixed in PR #528
