### ISSUE TITLE
Populates with too many categories

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#505]
My two projects only have the bare minimum categories that are in the project by default.

<img width="467" alt="image" src="https://github.com/rmlockwood/FLExTrans/assets/4039852/723c0754-232e-42f0-9af4-93b89971b533">

But when I run the module "Set up transfer rule categories and attributes", it brings a lot more in.

<img width="242" alt="image" src="https://github.com/rmlockwood/FLExTrans/assets/4039852/420826f4-93db-4524-92bc-c6800c05f909">

How did it decide which ones to bring in?  (These look like they came from the French-Spanish projects.)

**Comment by rmlockwood** [comment]
Can you reproduce this? I'm wondering if the config file was still set to Spanish or something.

**Comment by rmlockwood** [comment]
Can't reproduce.
