### ISSUE TITLE
[Synthesis] "Is abstract form" doesn't prevent an allomorph from being chosen

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#507]
I added an allomorph because I know it occurs.  But I'm not ready to specify its environment, so I made it "Is abstract form".  However, it is still getting chosen as the "elsewhere allomorph" (because it has no environment).

Allomorph definition:
<img width="393" alt="image" src="https://github.com/rmlockwood/FLExTrans/assets/4039852/bfbf086e-0d80-45e2-abbd-df607f1640ee">

Word that should get i- prefix (Lexeme Form):
<img width="440" alt="image" src="https://github.com/rmlockwood/FLExTrans/assets/4039852/1b8b664b-5f77-40f3-90af-868f0e93937d">

**Comment by rmlockwood** [comment]
Also entries marked as Is Abstract Form should get ignored when creating the bilingual lexicon.
Also, maybe there should be a check on the interlinear text that no morpheme used is an abstract form. This would produce an error.

**Comment by bbryson** [comment]
But "Is Abstract Form" only applies to allomorphs (including the Lexeme Form)--it isn't normally considered to apply to an entire entry.  If an entry consists only of allomorphs that are marked as Abstract (including the case where there is only a Lexeme Form and that form is marked as abstract), then it is not clear to me what that entry is for.  The parser would not ever recognize it as part of a word in the interlinear.  Manual interlinearizing would allow it though.    We would need to understand more about what this kind of entry is trying to do, to understand how to treat it for FLExTrans.

**Comment by rmlockwood** [comment]
On second thought, I'm not going to ignore lexeme forms that are marked as abstract since other allomorphs could be valid. We could at some point check if all forms are marked as abstract and ignore them.
This is now fixed for synthesis and will be in the next version.
