### ISSUE TITLE
[Rule Assistant] Should be able to click on the target word category to get the menu

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#620]
Right now the only way to get the context menu is to click on the target word text, e.g. word1, but it would be nice if the menu came up when clicking on the category text as well.

**Comment by AndyBlack** [comment]
Fixed in version 0.10.0 of the Rule Assistant UI

**Comment by rmlockwood** [comment]
This capability should also be possible on the source words.

**Comment by AndyBlack** [comment]
I'm confused.
For source words: if you click on "word" you get the word menu items; if you click on the category, you get the category edit items.
For target words: if you click on either the "word" item or the italicized category item, you get the word menu items.
What exactly do you want changed?

**Comment by rmlockwood** [comment]
The current behavior is appropriate.
