### ISSUE TITLE
[Rule Assistant] Rule should get created in the transfer rules file even if one exists with the same name.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#621]
According to the first logic specifics requirement on the Trello board, the tool should create a rule with copy (1) or the like appended to it when a rule with the same name already exists. If necessary, copy (2) ... should get created.

If there's not a good reason to allow this, please explain.

**Comment by mr-martian** [comment]
I see now that I misinterpreted "will not overwrite".

**Comment by rmlockwood** [comment]
verified that it's fixed in RA build 29
