### ISSUE TITLE
[Rule Assistant] Create permutations doesn't become enabled

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#622]
I created 3 words on the target side, but I didn't get the Create permutations checkbox to become enabled. Only after I had marked one of the words as head and changed to another rule and came back did it become enabled.

**Comment by AndyBlack** [comment]
Fixed in version 0.10.0 of the Rule Assistant UI

**Comment by rmlockwood** [comment]
verified
