### ISSUE TITLE
[Rule Assistant] No FLExTrans icon on test machine

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#624]
When I run the RA on my machine I get the FLExTrans icon showing on the status bar. When I run it on a test machine, I get the Java icon. 
![image](https://github.com/rmlockwood/FLExTrans/assets/7088137/70c2f630-2466-4771-b108-21374dbb0279)

**Comment by AndyBlack** [comment]
What do you mean by "a test machine"?

**Comment by rmlockwood** [comment]
Ok. I got a FLExTrans icon for some reason when I ran it in by dev environment. Is it possible to have it use the icon here? https://github.com/rmlockwood/FLExTrans/blob/master/FLExTransInstallIcon32.ico

**Comment by AndyBlack** [comment]
No, .ico files do not work.  I did change to use the FLExTransIcon.png file, though.  See version 0.10.1 of the Rule Assistant UI.

**Comment by rmlockwood** [comment]
After reinstalling FT that has the new RA, I still don't get the FT icon on the status bar. Do I need to uninstall the RA?

**Comment by rmlockwood** [comment]
I'm talking about the icon on the bottom status bar in Windows.

**Comment by AndyBlack** [comment]
Ah, that's called the taskbar.  I see that it is this way for me after installing, too.  Interestingly, when I run it from my Java IDE, it shows correctly...
I'll look into it.

**Comment by AndyBlack** [comment]
Do you have a png or ico file for the icon that is 128x128?  Mine is just 32x32 and that might be part of the problem.

**Comment by AndyBlack** [comment]
No, that was not it.  It turns out that having spaces in the file name caused the problem.
So, starting with version 0.11.0, it will be in C:\Program Files\FLExTransRuleAssistant as FLExTransRuleAssistant.exe.  You should uninstall the previous version.

**Comment by rmlockwood** [comment]
Fixed in 0.11.0 FT 3.11 build 49
