### ISSUE TITLE
[Rule Assistant] Duplicate rules messes up the word numbering

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#633]
When I duplicated a 3 word rule, the new rule ended up with word4 everywhere.

**Comment by AndyBlack** [comment]
See if this is fixed in version 0.10.0 of the Rule Assistant UI

**Comment by rmlockwood** [comment]
verified

**Comment by rmlockwood** [comment]
This bug seems to be back. I right-click to duplicate the first rule and the new rule has all the words with number 4.
[RuleAssistantRules.txt](https://github.com/user-attachments/files/15569128/RuleAssistantRules.txt)

**Comment by AndyBlack** [comment]
Fixed in version 0.12.1 at https://drive.google.com/file/d/1DX5Sn40vVaJzDVgpThq6cTL4UCW2t9V9/view?usp=sharing
(When duplicating a word, we want to use a new id number but when duplicating a rule, we do not.)

**Comment by rmlockwood** [comment]
Verified.
