### ISSUE TITLE
[Rule Assistant] Give an error to the user on create when these conditions exist

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#636]
Here's some ideas on ill-formed agreement rules that should generate errors in the UI:

1. ~Only one word exists under the target phrase.~ 
2. No categories have been assigned to the source words.
3. No target word has been marked head. (Maybe word1 should start out defaulting to head?)
4. No features have been assigned to target words or affixes.

**Comment by mr-martian** [comment]
I've added checks for 2 and 3.

Once we expand beyond strictly doing agreement rules, I can easily imagine 1 (deleting a function word) or 4 (reordering non-inflected words) being intentional.

**Comment by rmlockwood** [comment]
Andy, can you put UI error messages in if the user tries to create when these conditions exist? The tool should save the changes the user made, give an error, but not exit.

**Comment by AndyBlack** [comment]
Check out version 0.15.0 at https://drive.google.com/file/d/1cGe-CvUiW7JTa10t8HMyvLhY3JpZp5_5/view?usp=sharing.  It checks for numbers 2-4 (at least per my understanding of them).

**Comment by rmlockwood** [comment]
Working for me in 0.16
