### ISSUE TITLE
[Rule Assistant] Apertium rules that get created should allow other non-agreement affixes to be transferred

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#639]
This is a significant change, I think.
It's possible that the affixes involved in the agreement aren't the only affixes on the word. Right now we assume that the affixes with the features identified are the only ones present on the words.
I'm guessing the way to approach it would be to change the tags on the word and in the output portion of the rule, output 'whole'.

**Comment by mr-martian** [comment]
If you have a word with an affix that has something like `<Feature label="gender" match="potato"/>` where no other feature has `match="potato"`, then that affix will just be copied in place, so listing affixes that should be retained but which are not involved in agreement should already work.

**Comment by rmlockwood** [comment]
As we discussed a user may not want to mention one or more affixes that are not involved in agreement in the Rule Assistant. It would be nice if that could be handled.

**Comment by rmlockwood** [comment]
Not to be implemented right now.
