### ISSUE TITLE
[Rule Assistant] Give duplicate rule a different name

### ISSUE THREAD

**Issue by SaraMeiSL** [rmlockwood/FLExTrans#641]
When duplicating a rule, it would be nice if the duplicate rule automatically had a number or ‘copy’ added to the name to differentiate the two rules.

Current view:
![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/266cd589-9ef9-4dea-8a00-dc448caff80e)

**Comment by AndyBlack** [comment]
Fixed in version 0.10.1 of the Rule Assistant UI.
