### ISSUE TITLE
[Rule Assistant] unexpected behaviour on use of 'Move up' for newly duplicated rule

### ISSUE THREAD

**Issue by SaraMeiSL** [rmlockwood/FLExTrans#642]
Duplicate a rule
Rename the second instance
Use Move up on renamed rule

Unexpected behaviour where the original rule moves up, even though duplicate rule is selected.
NB - nothing was saved; NewRuleToTestMoveUp has had no edits, just a default rule

Before move up:
![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/ceb087b6-2acb-4393-a4df-e152bce278a6)

After move up:
![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/82b5033e-fd12-4b51-8977-b77bc2b1873e)

**Comment by AndyBlack** [comment]
Fixed in version 0.10.1 of the Rule Assistant UI.

**Comment by rmlockwood** [comment]
working 0.14.0
