### ISSUE TITLE
[Rule Assistant] 'change number' on second instance changes number on first instance

### ISSUE THREAD

**Issue by SaraMeiSL** [rmlockwood/FLExTrans#644]
The rule has word1, which is then duplicated and so there are two instances:

![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/fc8eac9c-b135-4f42-b1f1-70b0b35bbca4)

Change number is used on the instance on the RHS:

![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/de1851f5-7db4-4460-9a1f-211990e77e99)

![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/c6bab053-a55e-4f51-9be7-3337640dca63)

However, the word on the LHS is the one that is renumbered word2, whereas it was expected that the word on the RHS would be renumbered:

![image](https://github.com/rmlockwood/FLExTrans/assets/74278075/90a834ef-d935-4a32-a2ba-c29d2e389f67)

**Comment by AndyBlack** [comment]
Fixed in version 0.10.1 of the Rule Assistant UI.

**Comment by rmlockwood** [comment]
working 0.14.0
