### ISSUE TITLE
[Rule Assistant] Do smarter validation on which features can be added where

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#645]
As discussed by email, with valid feature information that is fed to the UI, the tool can do smart validation on features and how they can be applied to different stems or affixes.

**Comment by AndyBlack** [comment]
Version 0.11.0 fixes this.  See https://drive.google.com/file/d/1L-jDph5ULiXs9w4MefsI-qe1saK-XEKA/view?usp=sharing

**Comment by rmlockwood** [comment]
Verified in 3.11 build 49
