### ISSUE TITLE
[Import from Paratext] Import from Paratext missing some books

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#652]
I was trying to import chapters from Paratext, but some of them got missed.  I've sent the source files by email; I don't want to attach them to the GitHub issue because I haven't asked permission for that.

For Luke, I tried to import chapters 1-24, but only 1-19 came in.
For Genesis I tried to import chapters 1-3 but only 1-2 came in.

**Comment by rmlockwood** [comment]
It seemed to work for me today. No missing chapters. I'm using the new 3.11.4 version of the module on the master branch.

**Comment by bbryson** [comment]
Okay, I tried it in the 3.11.1.1 build from today (or yesterday?), and it seems to work.  Okay, great!
