### ISSUE TITLE
[Rule Assistant] Default feature not working in French Spanish pair

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#654]
See the files in the French-Spanish Advanced folder. The noun should default to singular number when not marked with a suffix. Currently the backend doesn't create a valid macro for sg as default. See image below.

![image](https://github.com/rmlockwood/FLExTrans/assets/7088137/0d863eb0-d719-4d07-bb5a-bedf39d73881)

**Comment by mr-martian** [comment]
Is this an instance where the target affix is null?

**Comment by rmlockwood** [comment]
The target affix is not null for singular, it's just not there. In my UI rule, I'm trying to say if there is no number affix, assume that the word is singular. The effect is that for a singular noun, no affix gets put on the target (Spanish) noun and also no affix gets put on the adjective for number. (maybe we need to say default for number on the adj is also singular?) In the plural noun case, the affix is there marked as plural and that should trigger agreement with the adjective which will cause a plural number suffix on the adj.

**Comment by rmlockwood** [comment]
This is working now! Thanks.
