### ISSUE TITLE
[Rule Assistant] The UI should allow affixes to be created on the source words.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#655]
Right now Insert Prefix/Suffix is not an available option on the Source part of the phrase.

**Comment by AndyBlack** [comment]
Version 0.16.0 of the UI tool now enables inserting affixes on the source phrase.  See https://drive.google.com/file/d/1v2L1LgMv1ZIxqJS-ES-9K0XGYb4Vptdx/view?usp=drive_link.

**Comment by rmlockwood** [comment]
This works for me in 0.16
