### ISSUE TITLE
[Rule Assistant] Set value for feature not working in German Swedish pair

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#656]
The macro created is not coming out right when turning a separate word into a suffix. See the German Swedish folder in the Sample Rules folder. See image for what I'm getting.

![image](https://github.com/rmlockwood/FLExTrans/assets/7088137/5483e018-eb79-4ecd-bf86-80a6705e692a)

**Comment by mr-martian** [comment]
I don't seem to have the German and Swedish FLEx projects.

**Comment by bbryson** [comment]
I moved things around, because there were sample files in several different places.  Now they are all in one place:  https://drive.google.com/open?id=17SfITMaV9E_h5qHzn295LRr8Tc3ykd20&usp=drive_copy   Inside that folder there is one called German Swedish - Word to Suffix

All of the other sample data is there as well.

**Comment by rmlockwood** [comment]
Did you find it?

**Comment by rmlockwood** [comment]
Ok. That seems to work now. That was using a rule that had the target phrase with both a number suffix and a definiteness suffix.
Now if I change it to just be one suffix that has both number and definiteness features on it. I get a macro with no choose statement. I expected a choose statement that would check the number feature of the noun. See attached rule from the GUI and the image of the macro I'm getting.
[RuleAssistantRules.txt](https://github.com/user-attachments/files/16069366/RuleAssistantRules.txt)
![image](https://github.com/rmlockwood/FLExTrans/assets/7088137/a96dea41-cc42-4b66-9e74-5127ff5a3809)

**Comment by rmlockwood** [comment]
This works. I'm getting multiple-affix-for-defid-sg for the singular case which is correct because two affixes have sg.
Now I've revised my target noun to have gender included to distinguish between the two singular suffixes. But I don't get anything with gender in my macro. Attached is my new rule file. The output I'm getting is below.
[RuleAssistantRules.txt](https://github.com/user-attachments/files/16078093/RuleAssistantRules.txt)
![image](https://github.com/rmlockwood/FLExTrans/assets/7088137/83bb8234-0290-4ef2-b151-88060f80f265)

**Comment by mr-martian** [comment]
Your rule has a gender feature on the word, and a stem feature on the head word only has an effect if it agrees with something.

**Comment by rmlockwood** [comment]
Thanks for catching that! I added gender: alpha to the suffix. It works now in RA build 81.
