### ISSUE TITLE
[Rule Assistant] default feature needed on affix in UI

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#657]
We need the ability to say a default feature can be on a non-head word. Either on the root or on an affix.

**Comment by AndyBlack** [comment]
The fix is in UI version 0.17.0 at https://drive.google.com/file/d/1b26zCaBk9zg_ODYxV1k2AmP66me8h6do/view?usp=drive_link

**Comment by rmlockwood** [comment]
This is working in version 0.17
