### ISSUE TITLE
[Rule Assistant] French-Spanish default feature needed on affix

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#658]
For French-Spanish Advanced, the indefinite article in Spanish is unmarked in the masculine situation. So, I am marking the suffix on the indef as having feature label=gender match=α unmarked_default=m. See the Google Drive folder for the RuleAssistantRules.xml file (in the Build folder)
I expect to get no gender suffix on the indef, but right now I get m-NOTAG.

I'm also marking the suffix of the adjective with: unmarked_default="sg". I think this will make it unambiguous that singular doesn't get a suffix and there doesn't have to be an assumption of that.

**Comment by rmlockwood** [comment]
Here's some sample data to go with the rest of the data:
Input: 
une1.1 indf f sg pomme1.1 n f 
un1.1 indf m sg poisson1.1 n m

This 2nd line is where I get the m-NOTAG

**Comment by rmlockwood** [comment]
I'm still getting: un1.1 indf m-NOTAG pescado1.1 n    instead of the expected un1.1 indf pescado1.1 n

**Comment by mr-martian** [comment]
If I move the `unmarked_default="m"` to the noun, then it works for me after [c2045f5](https://github.com/rmlockwood/FLExTrans/commit/c2045f576b7c0ed47b6bede20599a896b96d76ca)

**Comment by rmlockwood** [comment]
Putting unmarked_default="m" on the noun to me means 'some of my nouns may not be marked for gender and in that case assume they are masculine'. What I'm trying to say by putting unmarked_default="m" on the suffix is 'normally I would have a gender suffix for masculine and feminine, but when the noun is masculine, there won't be a suffix.' 
There may be situations where I mark the noun as defaulting to masculine, but the indefinite suffix would have both a possible masculine and feminine suffix. Going from Spanish to French and analyzing le and la as l -def.m.sg and l -def.f.sg would be an example.
