### ISSUE TITLE
[Rule Assistant] Rule N (1) gets created with macro m_n_affix_from_n2

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#661]
It would be nice if the numbers were the same. Both 1 or Both 2.

**Comment by mr-martian** [comment]
In more complicated rules, we'd have multiple macros, and we couldn't name any of them until we knew what all of them were, which would make the control flow a lot more convoluted.

I think a better solution would be to have the rule generator use the comment field (`c=`) in macro definitions to encode what the macro does and then reuse it in subsequent runs.

**Comment by rmlockwood** [comment]
Please undo this solution. When I do multiple runs of the RA, I'm finding that it won't update a macro that already exists. I would rather have multiple macros where I know the last one is the one that just got created.

The main point of this issue was to use the same starting index number. My preference is to start the index at 1 for both. So, in most cases, Rule N (1) would use macro m_n_affix_from_n1.

**Comment by rmlockwood** [comment]
Fixed in RA build 88
