### ISSUE TITLE
Spanish-French Ranking not working

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#663]
I attempted to create a rule for Def-Noun, but the ranking isn't being taken into account.

Here's the Google drive where the projects are:
https://drive.google.com/drive/folders/1PhD2IKj-TZ6A1ncpD63swTyrwDoM02Gs

**Comment by rmlockwood** [comment]
I'm still not getting a place in the lemma macro that puts out the option les1.1 when I run the Def N rule. I don't think I saw any change to the macro compared to before.

**Comment by mr-martian** [comment]
I changed the structure to the following and it worked:
```
def
  number: default=sg, rank=1
  gender: rank=2
n
  gender
  suffix
    number
```

**Comment by rmlockwood** [comment]
Working in RA build 84
