### ISSUE TITLE
Add description field to Rule Assistant UI

### ISSUE THREAD

**Issue by AndyBlack** [rmlockwood/FLExTrans#665]
This description field would be for the user to note why s/he wrote the rule.  It could include sample source/target data, say, and/or what motivated the rule.
It could appear immediately below the Rule Name field.

**Comment by rmlockwood** [comment]
Good idea. I like it.

**Comment by AndyBlack** [comment]
Version 0.18.0 of the Rule Assistant UI has a description field now.  See https://drive.google.com/file/d/1ZeV7l-XsyvCc5XHttK_eMboL2IF3R_Vb/view?usp=sharing.

**Comment by rmlockwood** [comment]
@AndyBlack I expected the description field to automatically wrap. Is that possible?

**Comment by rmlockwood** [comment]
@mr-martian I didn't see a comment show up in my rules. I updated the Evok folder with a new RuleAssistantRules.xml file with descriptions. See if it works for you.

**Comment by mr-martian** [comment]
> @mr-martian I didn't see a comment show up in my rules. I updated the Evok folder with a new RuleAssistantRules.xml file with descriptions. See if it works for you.

I don't see a description field in the rules file in that project.

**Comment by AndyBlack** [comment]
Added an automatic wrapping capability.  I should have thought of that...  Version 0.19.1 has the fix.  See https://drive.google.com/file/d/1wHUFIq1b3WAgosAZsOaxYTsGq6coJ90a/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in RA UI 0.19.1 The Apertium rule now has the description. Verified in RA build 94.
