### ISSUE TITLE
[Rule Assistant] UI Need a way to add a word to the target side that doesn't exist on the source side.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#674]
We have the backend working to support a word with an affix that translates to the word plus an additional word.
We need the UI to somehow support adding this independent word.
Attached is a hand-created version of the xml rule that currently works with the backend.
[RuleAssistantRules.txt](https://github.com/user-attachments/files/16268997/RuleAssistantRules.txt)

**Comment by AndyBlack** [comment]
Will need to allow ability to insert a category on a target word which does not have a corresponding source word.  I think we can then insert features on this new word.

**Comment by AndyBlack** [comment]
Added in version 0.20.0 at https://drive.google.com/file/d/19LqoXA4Gse9sPLVewLjNhG-rRN6DUUXU/view?usp=sharing

**Comment by rmlockwood** [comment]
working in 0.20.0
