### ISSUE TITLE
[Rule Assistant] UI Mark all features with a ranking when ranking is desired

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#675]
As @mr-martian mentions in #666, the backend only takes ranking into account if all the features on a suffix (presumably also a root) have ranking set to something.
It would be nice if the UI made this easy for the user. Maybe when the user assigns a ranking to one feature, the tool automatically gives the remaining features a ranking. The user can then modify those later. Also, removing a ranking from one would remove it from all.

**Comment by AndyBlack** [comment]
Do you want the ranking to be set automatically on just the other features in the affix or on the features in the word or on all the features in the phrase?
Similarly, when deleting a ranking, do you want the ranking removed from the other features in the affix or the word or the phrase?

**Comment by rmlockwood** [comment]
I think just apply ranking changes on a single affix or on the word. Each affix basically represents a new Apertium, so the ranking can be on for one and off for another.

**Comment by AndyBlack** [comment]
Added to UI version 0.22.0.  See https://drive.google.com/file/d/1TPzIKpNRBnrLY2lo6Apgec76eUDlUwY5/view?usp=drive_link

**Comment by rmlockwood** [comment]
Verified in 0.22.0
