### ISSUE TITLE
[Rule Assistant] UI help - add info. about ranking

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#691]
All features have to have a ranking for ranking to take effect.

**Comment by AndyBlack** [comment]
Please make some suggestions of what it should say.

**Comment by rmlockwood** [comment]
What you have in the help is good. Maybe just add. 'Please realize that if all the features on this word or affix do not each have a ranking value, ranking will be ignored by the Rule Assistant.'

**Comment by AndyBlack** [comment]
Added in version 0.24.0.  See https://drive.google.com/file/d/1sf_WM26SoWpeGEy2_YxfHzvLPfRSK8dx/view?usp=sharing

**Comment by rmlockwood** [comment]
Great, thanks.
