### ISSUE TITLE
[Run Apertium] Extra newlines with new Apertium tools in advanced transfer mode

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#712]
The new Apertium tools create an extra newline after each line of text in the target text file.

There used to be one extra newline now there are two. It would be great if there were none.

See test data here: https://drive.google.com/drive/folders/1AGwyYmKCWJyUBKSfiXT4tzyiHAG4-uYG?usp=drive_link

**Comment by mr-martian** [comment]
This is https://github.com/apertium/apertium/issues/172

**Comment by rmlockwood** [comment]
Closing this for now since I don't know when Apertium will get fixed.
