### ISSUE TITLE
[Replacement Dictionary Editor] Remove warning for entries that have no affixes

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#715]
We have a message that says:
![image](https://github.com/user-attachments/assets/725b5eb4-a6da-4164-a86a-12392d33a384)
I think we need to get rid of this.
We sometimes want to replace an entry in the bilingual lexicon where the source is the same as in biling. lex., but the target has some kind of inflection. 
E.g. xyz1.1<pers> -> abc1.1<pers><obl>
Therefore, we don't need to give a warning when there are no affixes.
I guess if there were no affixes on either side, that would deserve a warning.

**Comment by rmlockwood** [comment]
Sometimes there's a tag that can be both an affix and a feature. I think when loading the replacement file the tool should work from right to left. Check if the rightmost symbol is an affix. If it is leave it in the affix slot then go to the next one. Once no affix is found, the rest of the symbols would be features/classes (except the gram. cat., of course).

**Comment by rmlockwood** [comment]
It looks like enclitics (and presumably proclitics) may not be being treated properly as 'suffixes' for the Replacement editor. In the test data below, obl is an encltic that should show up in the affix column.
[f-t](https://drive.google.com/drive/folders/1yxycuO_KhmiIjMbTHPYfAASHXgvVkkBs?usp=drive_link)

**Comment by mr-martian** [comment]
working for me now

**Comment by mr-martian** [comment]
16837f0 is also relevant

**Comment by rmlockwood** [comment]
There's still a problem. rows 88-93 have a single suffix, yet they are showing up in the Features/Classes column.

**Comment by mr-martian** [comment]
I opted to include `MoUnclassifiedAffixMsa` as well - can easily take that out if not wanted
