### ISSUE TITLE
[Rule Assistant] UI should add ranking value to a new feature added

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#716]
When the features on a word (or suffix) already have rankings set and a new feature gets added, the new feature should automatically get a ranking. (Maybe default to the lowest ranking).
Currently when I add a new feature and the other features having ranking, the new feature gets added without a ranking.

**Comment by AndyBlack** [comment]
Fixed in version 0.24.1 at https://drive.google.com/file/d/1qHfoPf2HV7QsTCq2G1ejjrFLEjxpquE9/view?usp=sharing

**Comment by rmlockwood** [comment]
looks good.
