### ISSUE TITLE
[Rule Assistant] UI typo i -> I

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#717]
In the pop-up menu for the target phrase, when adding a suffix to a word, the menu option 'insert suffix' should have a capital I like the rest of the options.
![image](https://github.com/user-attachments/assets/eb15043b-76d0-43d6-9075-8318d98dcdbf)

**Comment by AndyBlack** [comment]
Fixed in version 0.24.1 at https://drive.google.com/file/d/1qHfoPf2HV7QsTCq2G1ejjrFLEjxpquE9/view?usp=sharing

**Comment by rmlockwood** [comment]
looks good.
