### ISSUE TITLE
[Rule Assistant] Make it easy to test Rule Assistant rules with test data

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#718]
See [Rule Assistant with Test Data](https://docs.google.com/document/d/1iPhf5DH6G6cljkXwes15_hNwgmqAyxNApN9Kff3qyrU/edit)

I would appreciate your feedback. We need to decide how the data interchange happens and how the new data is stored.

**Comment by rmlockwood** [comment]
@AndyBlack could you get the ball rolling by defining how you want information stored in the RuleAssistantRules.xml and in the ruleAssistantGUIinput.xml.

**Comment by rmlockwood** [comment]
@AndyBlack For the test data that's associated with a FLEx text, I was thinking that we could pass to you the data already in styled html format. This should be easy to display and you wouldn't have to have a complex xml structure to hold it. It would be one big blob of html data.

**Comment by AndyBlack** [comment]
It seems to me that this text information is completely independent of the RA GUI's data.  So couldn't we just pass the blob of html data in a separate (new) file to the RA GUI?  If this file is empty, we have scenario 2  If it has data, we have scenario 1 or 3.
The RA GUI will show whatever is in this file.
Upon exit, the return code could indicate cancel or the current rule or all the rules as we currently do.  We could add an additional flag to indicate whether to launch the LTR or not.

**Comment by AndyBlack** [comment]
@mr-martian I propose we change the invocation of the RA GUI tool as follows:
Add two new required items: 
1. the path to a HTML file with the needed styled HTML in it.
2. an indication of whether or not the invocation comes from the LRT or not.

That is, there are now four required arguments and one optional one:
<rule-file> <source/target-FLEx-category/features> <test-data-file> <came-from-LRT> (<max vars>)
The <test-data-file> is the HTML file.  The <came-from-LRT> is either a simple y (for yes) or n (for no).

Upon exit from the RA GUI, there will be an additional argument for returning to the LRT at the end of the output line by the RA GUI.  If it ends with " LRT" then it means to launch the LRT.  If it's not there, then return as normal.

Also, if there is no test data, then maybe have the HTML content be something simple like "No test data available" or some such.

Will that work for you?

**Comment by AndyBlack** [comment]
@mr-martian If it makes it easier to check out, there is a (temporary) new version with the additional command line arguments at https://drive.google.com/file/d/1AzOhoPfC2u4Kl8u0EXzCGMTL5wFg03WY/view?usp=sharing

**Comment by mr-martian** [comment]
Thanks Andy, that sounds relatively straightforward.

To clarify, I should extract `SourceTextName` from settings, convert the contents of this to Apertium format, pass that through the bilingual dictionary, and then render the result to HTML.

Does the GUI expect a complete HTML document or just a fragment?

**Comment by AndyBlack** [comment]
The GUI expects a complete HTML document.  It will merely load it into a web browser control.
As for the exact content and how to get it, I need to defer to Ron @rmlockwood

**Comment by rmlockwood** [comment]
@mr-martian, Yes, the `SourceTextName` is the text name we want to save. What I had in mind is to use the same function calls that the LRT uses to convert the data stream it got from the FLEx text to HTML. To that add the result of running the source data through Apertium and convert it to HTML. The result would then be lines of text where there is a source set of lemmas and symbols and a target set of lemmas and symbols. The formatted text would appear the same as in the LRT. See the mockup linked in the issue description. Does that make sense?

**Comment by rmlockwood** [comment]
@mr-martian Are your changes done now?

**Comment by mr-martian** [comment]
getting the data into RA is done, I still need to add opening RA from LRT and selecting which rules are enabled in the LRT

**Comment by mr-martian** [comment]
I think I've got it working now. Let me know if I missed any features.

**Comment by rmlockwood** [comment]
@AndyBlack Things are looking pretty good with the LRT. I'm wondering if we could give more screen real estate to the html window. I don't think the Description needs to have so much. The Description could possibly be as wide as the Rule Name. 
I really like the fact that the html box grows when you widen the whole window!
Here's what it looks like:
![image](https://github.com/user-attachments/assets/bce7d1a2-0121-41d5-a3a6-fb82fefa086e)

Also, here is the html file that goes with it for you to test with.

[RuleAssistantDisplayData.txt](https://github.com/user-attachments/files/17150295/RuleAssistantDisplayData.txt)

**Comment by AndyBlack** [comment]
@rmlockwood How does the new version at https://drive.google.com/file/d/1AzOhoPfC2u4Kl8u0EXzCGMTL5wFg03WY/view?usp=sharing seem?

**Comment by rmlockwood** [comment]
Yes, that looks much better.
Now the only issue is the buttons need to be big enough for the text in two places.
![image](https://github.com/user-attachments/assets/c0214dd3-fae9-4c4e-b76c-ada355b10675)

![image](https://github.com/user-attachments/assets/2d70cb7f-5c82-4576-9e9e-b7b2bc67155f)

**Comment by AndyBlack** [comment]
@rmlockwood  Try this new version at the same place: https://drive.google.com/file/d/1AzOhoPfC2u4Kl8u0EXzCGMTL5wFg03WY/view?usp=sharing

**Comment by rmlockwood** [comment]
@AndyBlack looks good

**Comment by rmlockwood** [comment]
@mr-martian the grammatical category is showing up in the html twice
![image](https://github.com/user-attachments/assets/f51b8694-1f07-487d-b9be-a0e271e1a30e)

**Comment by mr-martian** [comment]
fixed in https://github.com/rmlockwood/FLExTrans/commit/1d1977139d29ace89b324130243d28677f46acee, just forgot to tag it as such

**Comment by rmlockwood** [comment]
There are times when you want to go from the Rule Assistant to the Live Rule Tester, but you don't want to create any rules. You just want to use the rules that are already there. Can you (@AndyBlack & @mr-martian) give me that functionality. Keep in mind that the user might want to save the changes they've made.

**Comment by mr-martian** [comment]
@AndyBlack the output text starts with something other than `1` or `2` and contains `LRT`, then it will do what @rmlockwood is asking for.

**Comment by AndyBlack** [comment]
Added a return value of
0 LRT
for this case.  See version 0.27.0 at https://drive.google.com/file/d/1IdS0d8-uA_jR8eARNbi4l2c_Uo1k_O8w/view?usp=sharing

**Comment by rmlockwood** [comment]
Looks good and works well in 0.27.0
