### ISSUE TITLE
[Rule Assistant] Doesn't handle underspecified features on affixes properly

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#721]
In my Hindi-Lindi sample data, the nouns have these affixes, with these features:

M.SG    m sg
M.PL    m pl
F.SG     f sg   (this one might be missing from the sample data you have, but F.PL is there)
F.PL     f pl

But in adjectives it is:

aM.SG   m sg
aM.PL    m pl
aF.SP     f

When an affix is only specified for one of the features, that means that "any value" is allowed for the other feature, but the ones that ARE specified need to match.

Currently the Rule Assistant isn't handling this properly.  When the Noun has the F.SG affix, it should be assigning the aF.SP affix to the adjective.  Instead, it is assigning the aM.SG affix.  Same for F.PL and aM.PL.

 This relates to #724

**Comment by bbryson** [comment]
![07-FLEx-Adj Template](https://github.com/user-attachments/assets/d7d61441-6ffd-483f-8f6a-138d778db580)
![08-Wrong affix mapping](https://github.com/user-attachments/assets/61ad6121-920b-4ca1-8421-ac7cb6291d64)
![10-Underspecified features on suffixes](https://github.com/user-attachments/assets/d9f76ea6-b064-46f8-8b2d-445d015c3abb)

**Comment by mr-martian** [comment]
What's your Rule Assistant rule?

**Comment by bbryson** [comment]
[transfer_rules.txt](https://github.com/user-attachments/files/16972604/transfer_rules.txt)
![17-Rule Assistant Rule for Num Adj Noun](https://github.com/user-attachments/assets/9a3610f9-e0cf-4d70-81de-2247ced03875)

The projects are in the Hindi-Lindi folder with the Sample Data for the Rule Assistant.

**Comment by mr-martian** [comment]
Ah, if some of the affixes are only specified for some of the features, then the features should be ranked.

**Comment by bbryson** [comment]
I thought the ranking was for cases where "the absence of a suffix" has a meaning.  But in this case the F.Sg and F.Pl affixes are homographs, and rather than make them separate entries, they are a single entry that is unspecified for Number.   In some NPs, that affix represents F.Sg, and in other NPs it represents F.Pl.  And in different parts of the paradigm in different word categories, homographs like that will show up in different places--it could be for Masc.Nom and Masc.Obl somewhere else, so I think it would be hard to rank.  And it can be different in the Source and Target languages, as to which affixes combine.
  But maybe I need to hear more about what Ron intends with the ranking.

**Comment by mr-martian** [comment]
On the adjective affix, you should have gender as rank 1 and number as rank 2, meaning "first determine which set of affixes to consider based on gender, then consider number only if it's relevant (which it's not for `f`)".

**Comment by bbryson** [comment]
Okay, I hadn't understood what the ranking was for.  I was in fact hoping that the Rule Assistant could detect situations like this, but maybe that's asking too much.  I will need to work with the ranking functionality more to see how well it covers a variety of situations.

**Comment by bbryson** [comment]
Okay, I hadn't understood what the ranking was for. I was in fact hoping that the Rule Assistant could detect situations like this, but maybe that's asking too much. I will need to work with the ranking functionality more to see how well it covers a variety of situations.
