### ISSUE TITLE
[Rule Assistant] Features should be bold on the source side

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#723]
In the Rule Assistant, what would it mean for a feature on the source side to GET its value from somewhere else?  Shouldn't all of these be bold, to indicate that they are CONTRIBUTING the feature value?

![02-Source Features should be Bold](https://github.com/user-attachments/assets/bb9ea29c-b3b7-499e-bab1-b96efc0dd73c)

**Comment by bbryson** [comment]
Well, okay, when I wrote this I was forgetting that affixes "come across unchanged".  I still don't have a clear case of needing to look at features on the source side, though there may be one.  This can probably wait until we have an actual example of where affixes alone are not enough information, and we really do need to look at features on the source side.

**Comment by rmlockwood** [comment]
closing this for now.
