### ISSUE TITLE
[Extract Source Text] Support >> and > when used as punctuation.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#745]
Right now there are several problems with < and >.

1. If you make it part of the punctuation list in settings, the bilingual lexicon build fails.
2. Doing double >, the extract module only seems to handle one properly when the <> is in the punctuation list.
3. There is an error when converting to synthesis format in handling >. This might just be when <> is not in the punctuation list. But we need to test them being both part and not part of the punctuation list.

**Comment by bbryson** [comment]
For Quechua projects, the standard way to gloss markers for object agreement is with >    For instance, the project I was helping has glosses like:

>2
>3
1>2.FUT

Can this issue make it so > can be allowed in affix glosses also, or is that a separate issue?  (For now the team has changed their glosses.  But this is going to be standard across a lot of Quechua projects I would expect.)

**Comment by rmlockwood** [comment]
I think that's a separate issue. I've been experimenting with this and it's going to be a real pain to allow > within <>-delimited symbols. A lot of the parsing of symbols is done looking for <>. At the moment, I'm leaning toward disallowing <>. But, there should be an error message about it. The other Quechua project hasn't had this issue I'm not sure what they are using.

**Comment by rmlockwood** [comment]
Works now if the << or >> are part of the punctuation (non-Lexical Unit) stuff. Doesn't work for the case when the >< are listed as sentence punctuation. Also, glosses not handled for <>.
