### ISSUE TITLE
[Rule Assistant] UI problem with button label cut off on the disjoin features editor

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#750]
Here's the image of what I'm seeing.
![image](https://github.com/user-attachments/assets/a85b9e59-bdde-4eaf-b3e3-eb918225c2af)

**Comment by AndyBlack** [comment]
Fixed in version 0.26.0 at https://drive.google.com/file/d/16qe5X5DKYsbIUd3ng8ghgGixSw7vysrd/view?usp=sharing

**Comment by rmlockwood** [comment]
Verified in 0.26.0
