### ISSUE TITLE
[Rule Assistant] UI missing FLExTrans icon in save option dialog

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#751]
It would be nice if we could see the FLExTrans icon in the top left corner.

![image](https://github.com/user-attachments/assets/bef39335-0cf5-4850-98d5-678550be4749)

**Comment by AndyBlack** [comment]
Fixed in version 0.26.0 at https://drive.google.com/file/d/16qe5X5DKYsbIUd3ng8ghgGixSw7vysrd/view?usp=sharing

**Comment by rmlockwood** [comment]
Verified in 0.26.0
