### ISSUE TITLE
[Rule Assistant] UI issue - changing a title or description not detected for saving 

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#752]
If I change the title or description, there's no asterisk shown on the title bar. Also, I don't get prompted to save.

**Comment by AndyBlack** [comment]
Fixed in version 0.26.0 at https://drive.google.com/file/d/16qe5X5DKYsbIUd3ng8ghgGixSw7vysrd/view?usp=sharing
