### ISSUE TITLE
[Rule Assistant] UI buttons in pop-up dialogs are too close to the edge.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#755]
The Cancel button is too close to the edge. See below.

![image](https://github.com/user-attachments/assets/8c8575ae-b755-4cf9-af4c-262f246f9090)

**Comment by AndyBlack** [comment]
Fixed in version 0.26.0 at https://drive.google.com/file/d/16qe5X5DKYsbIUd3ng8ghgGixSw7vysrd/view?usp=sharing

**Comment by rmlockwood** [comment]
Verified in 0.26.0
