### ISSUE TITLE
[Rule Assistant] UI Tooltip needed for Test in LRT button

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#757]
Can we please put a tool tip on the Test in LRT that says 'Test in the Live Rule Tester tool.'

**Comment by AndyBlack** [comment]
Fixed in version 0.26.0 at https://drive.google.com/file/d/16qe5X5DKYsbIUd3ng8ghgGixSw7vysrd/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in 0.26.0
