### ISSUE TITLE
[Rule Assistant] UI Pop-up list windows too big

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#758]
The chooser windows that come up for inserting a feature or a category and the like are too big by default. See below. They just need to be wide enough to have the title not obscured. They don't need to be as tall either. A compact window with a list of values, even if you have to scroll would be more appropriate. I estimate that about half of the starting height and half the starting width might be about right.
Also, if would be nice the window could be centered on the screen or at least have the upper left corner roughly around the upper left corner of the main window. (lower and to the right of it might be better)

![image](https://github.com/user-attachments/assets/9b689256-f87e-404f-ba03-87a0fa3644d6)

**Comment by AndyBlack** [comment]
The UI remembers the size and location of each of these.  I can change the default size.  Note that with the message added for unmarked that we may want to make sure the feature chooser is wide enough for the message to show.

**Comment by AndyBlack** [comment]
Fixed in version 0.26.1 at https://drive.google.com/file/d/1g5VMr9OAxog6RABVTyhnQuUqZMo5CNkA/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in 0.27.0
