### ISSUE TITLE
[Rule Assistant] Need a way to overwrite a previously created Apertium rule

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#764]
Problem: 
Users may run the Rule Assistant multiple times until they get it working right. Each time they run it, they get 'rule name (1)', ...(2), ...(3), etc.

Solution: 
Add a check box that says something like 'Overwrite rule(s)' with maybe a ToolTip that says 'Overwrite previous rule(s) that have the same name.'

How it works:
When checked and the user creates rules, all rules in the rule file that have the name of the currently selected rule (or all rules if they click Create All) gets removed before the new rule gets created. Along with the rule, associated macros and variables also get deleted if they are not in use by a different rule.

Create permutations:
When Create permutations is also checked, all rules using the rule name in the permutation names and other (1) versions should be deleted with associated macros and variables.

It might be helpful if the permutation names have :: in the name so that they can be distinguished from other rule names.

**Comment by AndyBlack** [comment]
This seems to be a switch for the entire rule set.
How about we add an attribute overwrite_rules="yes" or "no" to the FLExTransRuleGenerator element?  @mr-martian Would that work for you Daniel?
We could put the check box just above the "Set disjoint features" button in the UI.
What think ye?

**Comment by mr-martian** [comment]
an attribute in the XML or a flag in the output - either would be fine with me

**Comment by rmlockwood** [comment]
@AndyBlack sounds good to me.

**Comment by AndyBlack** [comment]
What should the default be?  Shall we make the default be to overwrite?

**Comment by rmlockwood** [comment]
Yes, let's make the default be to overwrite.

**Comment by AndyBlack** [comment]
Version 0.28.0 at https://drive.google.com/file/d/1rveTyUAyq8u_wHiQ1nZ85YPAoJz96df_/view?usp=sharing has this addition.
@mr-martian Note that the DTD has been updated; see https://github.com/AndyBlack/ftrulegen/blob/master/FLExTransRuleGenerator.dtd
The default is to overwrite, but unless the user changes something then the XML file may not have the new overwrite_rules attribute on the FLExTransRuleGenerator element.

**Comment by rmlockwood** [comment]
@mr-martian old macros and variables are not getting deleted.

**Comment by rmlockwood** [comment]
It's working really good now. Macros and variables are being deleted or replaced. One small issue I noticed. The comments on the variables are not being deleted. Here's an example:
After creating a rule that uses two variables I get this:
![image](https://github.com/user-attachments/assets/512999e3-2242-4b19-8626-96658009f856)
After creating the rule again in overwrite mode I get this:
![image](https://github.com/user-attachments/assets/f384f91e-cd79-49f5-a87a-9a8f4c0945f8)

Please clean up the comments on the variables.

**Comment by rmlockwood** [comment]
Fixed in PR #771

**Comment by rmlockwood** [comment]
Overwrite and ordering rules is not working for Bantu rules (ones created with disjoint gender features). @mr-martian can you have a look?

**Comment by mr-martian** [comment]
As in the rules don't get deleted? Or the macros? (This is a downside of clearing macros one at a time, I should probably refactor the loop a bit.)

**Comment by rmlockwood** [comment]
Neither the rules or the macros are getting deleted. New rules are not getting put before old ones when overwrite is 'no'. It seems like all the overwrite and order logic isn't getting applied to Bantu rules.
