### ISSUE TITLE
[Rule Assistant] UI underscore is barely visible for target category

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#765]
Can we change the target category font to make the underscore show up better? Right now it is barely visible. (The underscore is added by FLExTrans to the FLEx category abbreviation because Apertium categories can't have spaces.) See image below.

![image](https://github.com/user-attachments/assets/2c881e67-bd69-4cde-a87d-db7ed9d40a27)

**Comment by AndyBlack** [comment]
Fixed in version 0.26.1 at https://drive.google.com/file/d/1g5VMr9OAxog6RABVTyhnQuUqZMo5CNkA/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in 0.27.0
