### ISSUE TITLE
[Rule Assistant] Test in LRT Save dialog has button with obscured label

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#767]
![image](https://github.com/user-attachments/assets/6a2b0a69-1ab2-483e-956f-347131678693)

**Comment by AndyBlack** [comment]
Sigh.  I forgot that running from the IDE does not do this, but running from an installed executable does.  There's a fix in version 0.28.0 at https://drive.google.com/file/d/1rveTyUAyq8u_wHiQ1nZ85YPAoJz96df_/view?usp=sharing

**Comment by rmlockwood** [comment]
Fixed in 0.28.0
