### ISSUE TITLE
[Rule Assistant] UI Create permutations checkbox stays checked when target word 3 is deleted

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#772]
The tool correctly grays out the Create permutations checkbox when the target words are down to 2 (maybe in the future 1), but the box is still checked and I think this 'True' value is ending up in the xml file.
The box should either be unchecked and grayed out or whenever the checkbox is disabled, the tool shouldn't send a True value for creating permutations.

**Comment by AndyBlack** [comment]
Fixed in version 0.28.1 at https://drive.google.com/file/d/1zC7AwmiTBH9sDXYIMSiMRrB9pUc1fn9g/view?usp=sharing

**Comment by rmlockwood** [comment]
Working in 0.28.1
