### ISSUE TITLE
[Rule Assistant] UI Typos in the screenshot image

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#785]
![image](https://github.com/user-attachments/assets/6c77410f-644d-455a-92a4-2d36b33d9d9b)

**Comment by AndyBlack** [comment]
Fixed in version 0.29.0 at https://drive.google.com/file/d/1S_runPY3Mr7rd_rTrxBkcJOCQMaZLzid/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in 0.30.0
