### ISSUE TITLE
[Rule Assistant] UI help doc should describe the test data pane

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#787]
Possible verbiage:
In the upper right corner is the data from the active source text as defined by FLExTrans. It is intended to display test data that you can consult as you define your rules in the Rule Assistant. Each line has source and target words and applicable features in data stream format which is similar to what you would see in the Live Rule Tester module. Note that the target words (with features) are the words that have been linked from the source words. Also, source affixes are carried over to the target words. Important: no transfer rules have been run.

**Comment by AndyBlack** [comment]
Fixed in version 0.29.0 at https://drive.google.com/file/d/1S_runPY3Mr7rd_rTrxBkcJOCQMaZLzid/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in 0.30.0
