### ISSUE TITLE
[Rule Assistant] UI issue with create permutations drop-down. Value changes back and forth.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#805]
I set it to 'Including head-only rule', go to another rule and come back and the value is changed to 'Omitting head-only rule'. Go back again and it changes back. See video below.
https://github.com/user-attachments/assets/cd11e8c8-818d-4013-8bb3-0985cf4c86b4

**Comment by AndyBlack** [comment]
Fixed in version 0.30.3 at https://drive.google.com/file/d/1Gt_Zx0YJVGc1WF6oAlLH_DjfWzaC-KRJ/view?usp=sharing

**Comment by rmlockwood** [comment]
Fix verified in 0.30.3
